export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  difficulty?: "easy" | "medium" | "hard";
}

export const questionsBank: Question[] = [
  {
    id: 1,
    question: "गति कितनी है?",
    options: ["4", "8", "5", "3"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 2,
    question: "बहनें कैसे तिलक करती हैं?",
    options: ["बादाम आकार का", "सीधी लाइन", "टेढ़ी लाइन", "गोल आकार का"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 3,
    question: "समवसरण में कितने स्टेप्स हैं?",
    options: ["50,000", "80,000", "1,00,000", "30,000"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 4,
    question: "श्रावक के व्रत कितने हैं?",
    options: ["8", "5", "12", "3"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 5,
    question: "सबसे श्रेष्ठ गति कौन सी?",
    options: ["मनुष्य गति", "देव गति", "तिर्यंच गति", "नरक गति"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 6,
    question: "पंचइन्द्रिय सूत्र का दूसरा नाम क्या है?",
    options: ["आलोचना प्रतिक्रमण सूत्र", "गुरु स्थापना सूत्र", "गमना गमने सूत्र", "शक्रस्तव सूत्र"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 7,
    question: "धर्म की माता कौन?",
    options: ["जैना", "करुणा", "परमोधर्म", "अहिंसा"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 8,
    question: "कितने कर्म हैं?",
    options: ["12", "5", "8", "3"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 9,
    question: "लघुशान्ति की रचना किसने की?",
    options: ["श्री मुनिसुंदरसूरि", "श्री जीवविजयजी", "श्री मसतुमुनि", "श्री मानदेव सूरि"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 10,
    question: "भैया कैसा तिलक करते हैं?",
    options: ["बादाम आकार का", "गोल आकार का", "सीधी लाइन", "टेढ़ी लाइन"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 11,
    question: "श्रावक की माता कौन?",
    options: ["अहिंसा", "करुणा", "वात्सल्य", "जैना"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 12,
    question: "ज्ञान की देवी कौन हैं?",
    options: ["दुर्गा देवी", "विद्या देवी", "सरस्वती देव", "पद्मावती देवी"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 13,
    question: "फूल पूजा को क्या कहते हैं?",
    options: ["पुष्प पूजा", "अंग पूजा", "धूप पूजा", "अक्षत पूजा"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 14,
    question: "कौन सी गति से मोक्ष जा सकते हैं?",
    options: ["देव गति", "मनुष्य गति", "तिर्यंच गति", "नरक गति"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 15,
    question: "कितने प्रकार की पूजा है?",
    options: ["12", "5", "3", "8"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 16,
    question: "बैल किसका लांछन है?",
    options: ["अर्णाथ भगवान", "आदिनाथ भगवान", "मुनिसुव्रत स्वामी", "सीमंदर स्वामी"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 17,
    question: "महाराज साहब को खाना देते हैं उसे क्या कहते हैं?",
    options: ["वोहराणा", "गोचरी", "वंदन", "पुण्य"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 18,
    question: "जीव रक्षा एवं संयम का सिम्बल क्या है?",
    options: ["नवकारवाली", "आसा", "रजोहरण", "दण्डासन"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 19,
    question: "भगवान के कितने कल्याणक हैं?",
    options: ["12", "5", "8", "3"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 20,
    question: "कौन सा आरा चल रहा है?",
    options: ["4", "6", "21", "5"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 21,
    question: "कौन से सूत्र से समाइक पालते हैं?",
    options: ["समइया वयजुतो", "करेमिभंते", "इच्छाकार", "इरियावहिया"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 22,
    question: "दर्शन करने से कितने उपवास का पुण्य मिलता है?",
    options: ["108 उपवास का", "1008 उपवास का", "1 वर्ष के उपवास का", "3 वर्ष का"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 23,
    question: "1 पानी के बूंद में कितने जीव होते हैं?",
    options: ["संख्यात", "असंख्यात", "अनंत", "1008"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 24,
    question: "पावापुरी तीर्थ में कौन से भगवान हैं?",
    options: ["महावीर स्वामी", "आदिनाथ भगवान", "पार्श्वनाथ भगवान", "नेमिनाथ भगवान"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 25,
    question: "भगवान कौन सी दिशा में देशना देते हैं?",
    options: ["पश्चिम", "उत्तर", "पूर्व", "दक्षिण"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 26,
    question: "पालितना का दूसरा नाम क्या है?",
    options: ["पावापुरी", "शत्रुंजय", "जूनागढ़", "शिखरजी"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 27,
    question: "स्वस्तिक क्यों बनाते हैं?",
    options: ["4 गति का नाश करने", "8 गति का नाश करने", "मोक्ष पाने", "देव गति पाने"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 28,
    question: "महावीर स्वामी की माता का नाम?",
    options: ["मारुदेवी माता", "सुरसुंदरी", "त्रिशला माता", "मयना सुंदरी"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 29,
    question: "सिद्ध भगवान के गुण कितने होते हैं?",
    options: ["12", "8", "5", "3"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 30,
    question: "समाइक कितने मिनट की होती है?",
    options: ["48", "45", "52", "30"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 31,
    question: "भगवान की पूजा करने से क्या पुण्य मिलता है?",
    options: ["108 वर्ष उपवास का", "1008 दिन उपवास का", "1000 वर्ष के उपवास का", "3 साल उपवास का"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 32,
    question: "सब तीर्थंकरों की माता कौन?",
    options: ["जैना", "करुणा", "अहिंसा", "वात्सल्य"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 33,
    question: "आयुष्य कर्म किसके जैसा होता है?",
    options: ["कुंभार", "चित्तारा", "भेदी", "बेड़ी जैसा"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 34,
    question: "भगवान किसमें बैठकर देशना देते हैं?",
    options: ["समवसरण", "सिंहासन", "कठासना", "कुर्सी"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 35,
    question: "आत्मा को संभाव रखने की क्रिया?",
    options: ["प्रतिक्रमण", "पूजा", "जाप", "समाइक"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 36,
    question: "कोल्ड ड्रिंक्स, आइसक्रीम, बिस्कुट को क्या बोलते हैं?",
    options: ["भक्ष्य", "सात्विक", "पात्विक", "अभक्ष्य"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 37,
    question: "पौषध कौन से सूत्र से पालते हैं?",
    options: ["समइया वयजुतो", "नवकार गिनके", "नमुत्थुणं", "सागार चंदो"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 38,
    question: "अंतराय कर्म किसके जैसा है?",
    options: ["कुंभार", "चित्तारा", "भेदी", "भंडारी"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 39,
    question: "ध्वजा कौन से रंग की होती है?",
    options: ["हरी", "पीली", "लाल और सफेद", "पीली और हरी"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 40,
    question: "सम्मेदशिखर तीर्थ में कौन से भगवान हैं?",
    options: ["पार्श्वनाथ भगवान", "महावीर स्वामी", "आदिनाथ भगवान", "नेमिनाथ भगवान"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 41,
    question: "उपाध्याय भगवंत के कितने गुण होते हैं?",
    options: ["27", "25", "52", "8"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 42,
    question: "रत्नत्रयी मतलब क्या?",
    options: ["तप, धर्म, कर्म", "ज्ञान, दर्शन, चरित्र", "धर्मध्यान, शुक्लध्यान, अवधिज्ञान", "वेदनीय, आयु, ज्ञान"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 43,
    question: "नरक कितनी हैं?",
    options: ["2", "5", "7", "8"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 44,
    question: "शत्रुंजय तीर्थ पर कौन से भगवान हैं?",
    options: ["शांतिनाथ भगवान", "पार्श्वनाथ भगवान", "आदिनाथ भगवान", "नेमिनाथ भगवान"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 45,
    question: "कर्मों की होली करने वाला पर्व?",
    options: ["ओली", "पर्युषण", "दीवाली", "होली"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 46,
    question: "भगवान के कितने अतिशय होते हैं?",
    options: ["12", "4", "8", "9"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 47,
    question: "श्रावक के अतिशय कितने?",
    options: ["124", "271", "356", "81"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 48,
    question: "पावपदजी का कौन सा नाम है?",
    options: ["मन", "आचार्य", "वचन", "काया"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 49,
    question: "वेदनीय कर्म किसके जैसा है?",
    options: ["द्वारपाल", "मदिरा जैसा", "मधु लिप्त तलवार", "सभी"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 50,
    question: "भगवान को मिठाई चढ़ाते हैं वो कौन सी पूजा है?",
    options: ["नैवेद्य पूजा", "फल पूजा", "धूप पूजा", "फूल पूजा"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 51,
    question: "तिथि कितनी होती है?",
    options: ["12", "5", "10", "8"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 52,
    question: "साधु-साध्वी और श्रावक-श्राविका को क्या कहते हैं?",
    options: ["परिवार", "संसारिक स्वजन", "चतुर्विध संघ", "सभी"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 53,
    question: "मोहनीय कर्म किसके जैसा है?",
    options: ["बेड़ी", "मदिरा", "चित्तारा", "सभी"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 54,
    question: "अरिहंत परमात्मा के कितने गुण?",
    options: ["27", "52", "12", "8"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 55,
    question: "आचार्य भगवंत के गुण कितने होते हैं?",
    options: ["12", "36", "24", "30"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 56,
    question: "नवकारमंत्र का दूसरा नाम क्या है?",
    options: ["आलोचना प्रतिक्रमण सूत्र", "गमना गमने सूत्र", "पंचपरमेष्ठी सूत्र", "गुरु स्थापना सूत्र"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 57,
    question: "विश्व का सबसे बेस्ट धर्म कौन सा है?",
    options: ["बौद्ध", "जैन", "पंजाबी", "मराठी"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 58,
    question: "उपासगधर्म सूत्र की रचना किसने की?",
    options: ["श्री भद्रबाहु स्वामी", "श्री हरिभद्र सूरि", "श्री जीव विजयजी", "श्री मुनिसुंदरसूरि"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 59,
    question: "भगवान जब भी जन्म होते हैं तब उसे कौन सा कल्याणक कहते हैं?",
    options: ["च्यवन कल्याणक", "निर्वाण कल्याणक", "जन्म कल्याणक", "मोक्ष कल्याणक"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 60,
    question: "नरक में कौन से देव पीड़ा देते हैं?",
    options: ["वैकांतिक देव", "परमाधामी देव", "भरत देव", "भ्रामिणी देवी"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 61,
    question: "लघु चैत्यवंदन कौन से सूत्र से करते हैं?",
    options: ["अरिहंत चेइयणम्", "इरियावहिया", "समइया वयजुतो", "लोग्गस"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 62,
    question: "पूजा कौन सी उंगली से की जाती है?",
    options: ["तर्जनी उंगली", "अनामिका उंगली", "पहली उंगली", "दूसरी उंगली"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 63,
    question: "महावीर स्वामी का दूसरा नाम क्या है?",
    options: ["आदिनाथ", "वर्धमान स्वामी", "नेमिनाथ", "पार्श्वनाथ"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 64,
    question: "तत्व कितने हैं?",
    options: ["12", "8", "30", "7"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 65,
    question: "8 कर्मों के राजा कौन हैं?",
    options: ["घाति कर्म", "मोहनीय कर्म", "अघाति कर्म", "वेदनीय कर्म"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 66,
    question: "महाराज साहब को रात को क्या बोलते हैं?",
    options: ["बाय", "त्रिकाल वंदना", "सी यू सून", "सभी"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 67,
    question: "भगवान की माता को कितने स्वप्न आते हैं?",
    options: ["12", "14", "8", "30"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 68,
    question: "अंतिम कौन से तीर्थंकर हुए?",
    options: ["पार्श्वनाथ भगवान", "नमिनाथ भगवान", "महावीर स्वामी", "नेमिनाथ भगवान"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 69,
    question: "महावीर स्वामी भगवान की हाइट क्या है?",
    options: ["8 हाथ", "7 हाथ", "7 फुट", "8 फुट"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 70,
    question: "अंतिम तीर्थंकर का नाम?",
    options: ["महावीर स्वामी", "पार्श्वनाथ भगवान", "नमिनाथ भगवान", "नेमिनाथ भगवान"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 71,
    question: "पूजा कितने टाइम करते हैं?",
    options: ["1 टाइम", "4 टाइम", "3 टाइम", "2 टाइम"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 72,
    question: "इंद्रिय कितनी हैं?",
    options: ["7", "8", "4", "5"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 73,
    question: "प्रातिहार्य कितने होते हैं?",
    options: ["8", "7", "5", "4"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 74,
    question: "शाश्वत मंत्र कौन सा है?",
    options: ["उपसागाहारम्", "नवकार मंत्र", "ॐ ह्रीं अरहं श्री पार्श्वनाथाय नमः", "सभी"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 75,
    question: "शाम के प्रतिक्रमण को क्या कहते हैं?",
    options: ["रैया प्रतिक्रमण", "समाइक", "देवसिया प्रतिक्रमण", "जाप"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 76,
    question: "नरक में जाने का गेटवे कौन सा है?",
    options: ["रात्रि भोजन", "अभक्ष्य", "सचित चीजें", "उपरोक्त सभी"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 77,
    question: "जैन भाई को देखकर क्या बोलते हैं?",
    options: ["हैलो", "प्रमाण", "वॉसअप", "नमस्ते"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 78,
    question: "पेपर प्लेट में खाने से कौन से कर्म का बंध होता है?",
    options: ["दर्शनावरणीय कर्म", "मोहनीय कर्म", "ज्ञानावरणीय कर्म", "अंतराय कर्म"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 79,
    question: "मंदिर में जाने से कितने उपवास का फल मिलता है?",
    options: ["108 उपवास का", "1 वर्ष के उपवास का", "1008 उपवास का", "3 साल उपवास का"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 80,
    question: "कितनी प्रदक्षिणा देते हैं?",
    options: ["7", "5", "3", "4"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 81,
    question: "सब साधु की माता कौन?",
    options: ["करुणा", "अष्टप्रवचन माता", "अहिंसा", "जैना"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 82,
    question: "सुबह उठते वक्त कितने नवकार गिनते हैं?",
    options: ["7", "8", "4", "5"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 83,
    question: "पूरे साल का पाप धोने के लिए कौन से प्रतिक्रमण करना चाहिए?",
    options: ["चौमासी प्रतिक्रमण", "संवत्सरिक प्रतिक्रमण", "देवसी प्रतिक्रमण", "मांगलिक प्रतिक्रमण"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 84,
    question: "जग-चिंतामणि सूत्र की रचना किसने की?",
    options: ["गौतम स्वामी", "नंदिसेन मुनि", "सिद्धसेन दिवाकर", "पुण्डरिकस्वामी"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 85,
    question: "दर्शनावरणीय कर्म किसके जैसा होता है?",
    options: ["द्वारपाल", "मदिरा जैसा", "भंडारी जैसा", "भेदी जैसा"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 86,
    question: "ध्वजा को देखकर क्या कहते हैं?",
    options: ["प्रणाम", "नमो जिनानम्", "नमस्कार महा मंत्र", "सभी"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 87,
    question: "महाराज साहब जो आहार लेने जाते हैं उसे क्या कहते हैं?",
    options: ["काप", "गोचरी", "पादिलेहन", "क्रिया"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 88,
    question: "महावीर स्वामी के प्रथम गंधार कौन?",
    options: ["500 गंधार", "गौतम स्वामी", "पुण्डरिक स्वामी", "नंदिवर्धन"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 89,
    question: "चौदस के प्रतिक्रमण को क्या कहते हैं?",
    options: ["पक्षी प्रतिक्रमण", "देवसी प्रतिक्रमण", "संवत्सरिक प्रतिक्रमण", "चौमासिक प्रतिक्रमण"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 90,
    question: "महाराज साहब किसमें खाना खाते हैं?",
    options: ["प्लेट्स", "हाथ में", "कशकुल", "पात्र"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 91,
    question: "महाराज साहब को देखकर क्या बोलते हैं?",
    options: ["मत्थेन वंदामि", "प्रणाम", "सुप्रभात", "सभी"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 92,
    question: "पंचपरमेष्ठी किसे कहते हैं?",
    options: ["सही उत्तर", "गलत उत्तर"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 93,
    question: "कौन से सूत्र को लघु प्रतिक्रमण सूत्र कहते हैं?",
    options: ["इरियावहियम्", "नमुत्थुणम्", "लोगस", "पंचइंद्रिय"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 94,
    question: "प्रथम तीर्थंकर का नाम क्या है?",
    options: ["सुविधिनाथ भगवान", "आदिनाथ भगवान", "सुपार्श्वनाथ भगवान", "मुनिसुव्रत स्वामी"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 95,
    question: "महावीर स्वामी के पिता का नाम क्या था?",
    options: ["नंदिसेन राजा", "सिद्धार्थ राजा", "नाभि राजा", "समुद्रविजय राजा"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 96,
    question: "ज्ञानावरणीय कर्म किसके जैसा है?",
    options: ["मंदिरा जैसा", "द्वारपाल", "आंखके ऊपर पट्टा", "भेदी जैसा"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 97,
    question: "4 महीने के पाप धोने के लिए कौन सा प्रतिक्रमण करते हैं?",
    options: ["चौमासिक प्रतिक्रमण", "संवत्सरिक प्रतिक्रमण", "देवसिया प्रतिक्रमण", "पक्षी प्रतिक्रमण"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 98,
    question: "यहाँ के मंदिर में मूलनायक भगवान कौन से हैं?",
    options: ["सही उत्तर", "गलत उत्तर"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 99,
    question: "सर्प कौन से भगवान का लांछन है?",
    options: ["मल्लिनाथ भगवान", "सुविधिनाथ भगवान", "पार्श्वनाथ भगवान", "सुपार्श्वनाथ भगवान"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 100,
    question: "महाराज साहब को देखकर क्या बोलते हैं?",
    options: ["मत्थेन वंदामि", "प्रणाम", "त्रिकालवंदना", "नमस्ते"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 101,
    question: "भगवान के मुख को देखकर क्या बोलते हैं?",
    options: ["नवकार मंत्र", "स्तुति", "स्तवन", "नमो जिनानम्"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 102,
    question: "जिनेश्वर भगवंत की आज्ञा धारण करने वाले को क्या कहते हैं?",
    options: ["स्थानकवासी", "जैन", "दिगंबर", "बौद्ध"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 103,
    question: "नाम कर्म किसके जैसा है?",
    options: ["जैना", "भेदी", "चित्तारा", "द्वारपाल"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 104,
    question: "कंदमूल में कितने जीव होते हैं?",
    options: ["अशंख्य", "संख्या", "1008", "अनंत"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 105,
    question: "गुरु वंदन कौन से सूत्र से करते हैं?",
    options: ["इच्छाकार", "अभूथियो", "खामासमन", "इरियावहिया"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 106,
    question: "कौन से सूत्र से समाइक लेते हैं?",
    options: ["करेमि भंते", "मुंहपत्ती", "खामासमन", "इरियावहिया"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 107,
    question: "शंखेश्वर तीर्थ में कौन से भगवान हैं?",
    options: ["शांतिनाथ भगवान", "पार्श्वनाथ भगवान", "नेमिनाथ भगवान", "महावीर स्वामी"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 108,
    question: "भगवान को फल चढ़ाते हैं वो कौन सी पूजा है?",
    options: ["फल पूजा", "पुष्प पूजा", "नैवेद्य पूजा", "अक्षत पूजा"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 109,
    question: "भगवान कितने दोष रहित हैं?",
    options: ["18", "15", "10", "20"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 110,
    question: "नमुत्थुणम् सूत्र का दूसरा नाम क्या है?",
    options: ["चैत्यास्तव सूत्र", "नामास्तव सूत्र", "उपरोक्त सभी", "शक्रस्तव सूत्र"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 111,
    question: "अभक्ष्य कितने हैं?",
    options: ["15", "20", "32", "42"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 112,
    question: "लोग्गस सूत्र का दूसरा नाम क्या है?",
    options: ["नामास्तव सूत्र", "शक्रास्तव सूत्र", "श्रुतास्तव सूत्र", "चैत्यास्तव सूत्र"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 113,
    question: "भगवान महावीर स्वामी के कितने गंधार हुए?",
    options: ["11", "8", "10", "15"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 114,
    question: "गुरु की आशातना कितनी?",
    options: ["56", "33", "74", "92"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 115,
    question: "नवकार में कितने अक्षर हैं?",
    options: ["86", "98", "69", "68"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 116,
    question: "मंदिर में एंटर होते टाइम क्या बोलते हैं?",
    options: ["निसीही", "आवसाही", "नमो जिनानम्", "सभी"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 117,
    question: "गोत्र कर्म किसके जैसा है?",
    options: ["कुंभार", "चित्तारा", "भेदी", "अहिंसा"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 118,
    question: "देवलोक कितने हैं?",
    options: ["7", "12", "8", "15"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 119,
    question: "कौन से जीव मोक्ष में जाते हैं?",
    options: ["भव्य", "अभव्य", "जाति भव्य", "अजाति भव्य"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 120,
    question: "जीवों के भेद कितने?",
    options: ["653", "586", "563", "536"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 121,
    question: "मंदिर की आशातना कितनी?",
    options: ["54", "64", "36", "84"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 122,
    question: "शंख किसका लांछन है?",
    options: ["नेमिनाथ", "नामिनाथ", "सुपार्श्वनाथ", "महावीर स्वामी"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 123,
    question: "तत्वप्रायी यानी क्या?",
    options: ["देव, गुरु, धर्म", "राग द्वेष, मोह"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 124,
    question: "पटाके फोड़ने से कौन से कर्म का बंध होता है?",
    options: ["मोहनीय कर्म", "दर्शनावरणीय कर्म", "वेदनीय कर्म", "ज्ञानावरणीय कर्म"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 125,
    question: "यहाँ पर बिराजमान बड़े महाराज साहब का नाम?",
    options: ["सही उत्तर", "गलत उत्तर"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 126,
    question: "महाराज साहब समाइक करते हैं या नहीं?",
    options: ["हाँ", "नहीं", "समाइक में ही रहते हैं"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 127,
    question: "अरिहंत परमात्मा कितने दोष रहित हैं?",
    options: ["20", "18", "9", "6"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 128,
    question: "राग-द्वेष को जीतने वाले को क्या कहते हैं?",
    options: ["वैगारी", "तीर्थंकर", "भगवंत", "आचार्य"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 129,
    question: "कितने आरे होते हैं?",
    options: ["5", "4", "6", "3"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 130,
    question: "भगवान के कितने अंगों पर पूजा करते हैं?",
    options: ["13", "9", "12", "10"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 131,
    question: "सकलतीर्थ सूत्र का दूसरा नाम क्या है?",
    options: ["श्री सिद्धसेन सूरि", "श्री हरिभद्र सूरि", "श्री नाम सेन सूरि", "श्री जीव विजयजी"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 132,
    question: "नवकारवाली में कितने मनके होते हैं?",
    options: ["108", "1008", "29", "40"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 133,
    question: "अष्टप्रकारी पूजा में प्रथम पूजा कौन सी है?",
    options: ["द्रव्य पूजा", "चंदन पूजा", "जल पूजा", "केसर पूजा"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 134,
    question: "जैन का सबसे महत्वपूर्ण त्योहार कौन सा है?",
    options: ["अट्ठाई", "पर्युषण", "ओली", "दिवाली"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 135,
    question: "महावीर स्वामी का लांछन क्या है?",
    options: ["सिंह", "शंख", "सर्प", "कमल"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 136,
    question: "महावीर स्वामी की हाइट कितनी थी?",
    options: ["8 हाथ", "7 हाथ", "7 फुट", "8 फुट"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 137,
    question: "गिरनार तीर्थ पर कौन से भगवान हैं?",
    options: ["नेमिनाथ", "नम्नाथ", "महावीर स्वामी", "धर्मनाथ"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 138,
    question: "स्त्री तीर्थंकर कौन से हुए?",
    options: ["आदिनाथ भगवान", "मल्लिनाथ भगवान", "धर्मनाथ भगवान", "मुनिसुव्रत स्वामी"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 139,
    question: "दीक्षा कल्याणक में भगवान क्या त्यागते हैं?",
    options: ["भोजन", "वस्त्र", "गहने", "संसारिक जीवन"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 140,
    question: "जैन धर्म के कितने मूल सिद्धांत हैं?",
    options: ["3", "7", "5", "9"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 141,
    question: "सिद्धक्षेत्र में कौन रहते हैं?",
    options: ["देव", "आचार्य", "गंधार", "मुक्त आत्माएं"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 142,
    question: "पद्मासन में कौन बैठते हैं?",
    options: ["तीर्थंकर", "साधु", "श्रावक", "उपासक"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 143,
    question: "केवलज्ञान प्राप्त होने के बाद तीर्थंकर को क्या कहते हैं?",
    options: ["सिद्ध", "आचार्य", "अरिहंत", "उपाध्याय"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 144,
    question: "जिनमंदिर में सबसे पहले क्या करना चाहिए?",
    options: ["प्रणाम", "दर्शन", "पूजा", "परिक्रमा"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 145,
    question: "त्रिकाल में कौन से काल आते हैं?",
    options: ["भूत, वर्तमान, भविष्य", "दिन, रात, संध्या", "प्रातः, दोपहर, सायं", "सुबह, शाम, रात"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 146,
    question: "जैन तीर्थंकरों में सबसे लंबे कौन थे?",
    options: ["आदिनाथ भगवान", "पार्श्वनाथ भगवान", "ऋषभनाथ भगवान", "महावीर स्वामी"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 147,
    question: "अहिंसा व्रत में कितने भेद हैं?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 148,
    question: "पंचपरमेष्ठी में अंतिम कौन आते हैं?",
    options: ["साधु", "आचार्य", "उपाध्याय", "सिद्ध"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 149,
    question: "आगम साहित्य किस भाषा में लिखा गया?",
    options: ["प्राकृत", "संस्कृत", "हिंदी", "गुजराती"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 150,
    question: "जैन कैलेंडर के अनुसार नया साल कब शुरू होता है?",
    options: ["कार्तिक शुक्ल एकम", "चैत्र शुक्ल एकम", "आश्विन शुक्ल एकम", "वैशाख शुक्ल एकम"],
    correctAnswer: 0,
    difficulty: "hard",
  },
];

export function getSequentialQuestions(count: number, usedIds: Set<number>): Question[] {
  const availableQuestions = questionsBank.filter((q) => !usedIds.has(q.id));

  if (availableQuestions.length === 0) {
    return [];
  }

  const toReturn = Math.min(count, availableQuestions.length);
  // Return questions in sequential order (as they appear in the array)
  return availableQuestions.slice(0, toReturn);
}
